### ISSUE TITLE
[Question] What is a 'enumerate object' ?

### ISSUE THREAD

**Issue by Igortorrente** [robertalks/udev-examples#2]
First of all, thanks for sharing your udev knowledge through these examples! Those are very helpful!!

Second, I'm asking this question because I did not find the de definition of 'enumerate object' in any udev documentation. If you don't mind, can explain the purpose at [udev_example2.c](https://github.com/robertalks/udev-examples/blob/master/udev_example2.c#L45)?

**Comment by robertalks** [comment]
Check this out: https://mirrors.edge.kernel.org/pub/linux/utils/kernel/hotplug/libudev/libudev-udev-enumerate.html

**Comment by robertalks** [comment]
no response.
